name: English Model

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Preprocess
      run: |
        wget http://data.keithito.com/data/speech/LJSpeech-1.0.tar.bz2
        tar xvf LJSpeech-1.0.tar.bz2
        python prepro.py
         
