name: English Model

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Dataset
      run: |
        wget http://www.openslr.org/resources/65/ta_in_male.zip
        unzip xvf ta_in_male.zip -d ta_in_male
        rm ta_in_male.zip

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: tamil

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
